"""PawPal+ app entrypoint."""

from datetime import datetime, timedelta

from pawpal_system import Owner, Pet, Scheduler, Task


def main() -> None:
    owner = Owner(name="Alex", contact_info="alex@example.com")
    pet1 = Pet(name="Biscuit", breed="Golden Retriever", age=4, sex="Male")
    pet2 = Pet(name="Mittens", breed="Tabby", age=2, sex="Female")
    owner.add_pet(pet1)
     

    # Create tasks OUT OF ORDER (not chronological)
    task3 = Task(
        description="Evening play",
        duration=20,
        frequency="daily",
        preferred_time_slot="18:00-18:30",
        time=datetime(2026, 6, 26, 18, 0),
        id="task-003",
    )
    task1 = Task(
        description="Morning walk",
        duration=30,
        frequency="daily",
        preferred_time_slot="08:00-09:00",
        time=datetime(2026, 6, 26, 8, 0),
        id="task-001",
    )
    task2 = Task(
        description="Lunchtime feeding",
        duration=15,
        frequency="daily",
        preferred_time_slot="12:00-12:30",
        time=datetime(2026, 6, 26, 12, 0),
        id="task-002",
    )
    task4 = Task(
        description="Afternoon nap check",
        duration=10,
        frequency="daily",
        preferred_time_slot="15:00-15:30",
        time=datetime(2026, 6, 26, 15, 0),
        id="task-004",
    )
    
    # Add tasks to pets
    owner.create_task(pet1, task3)  # Evening play to Biscuit
    owner.create_task(pet1, task1)  # Morning walk to Biscuit
    owner.create_task(pet2, task2)  # Lunchtime to Mittens
    owner.create_task(pet1, task4)  # Afternoon to Biscuit

    # Add two conflicting tasks for the same pet at the same time to trigger a warning
    conflict_time = datetime(2026, 6, 26, 10, 0)
    conflict_a = Task(description="Vet check A", time=conflict_time, duration=30, id="conflict-A")
    conflict_b = Task(description="Vet check B", time=conflict_time, duration=20, id="conflict-B")
    owner.create_task(pet1, conflict_a)
    owner.create_task(pet1, conflict_b)
    
    # Mark one task as completed
    task1.mark_complete(datetime.now())

    print(f"Owner: {owner.name}")
    print(f"Pets: {[pet.name for pet in owner.pets]}")
    print(f"Total Tasks: {len(owner.tasks)}")
    print()
    
    # Demonstrate SORT BY TIME
    print("=" * 50)
    print("DEMONSTRATION: sort_by_time()")
    print("=" * 50)
    scheduler = Scheduler(owner=owner)
    sorted_tasks = scheduler.sort_by_time()
    print("Tasks sorted by time (earliest to latest):")
    for task in sorted_tasks:
        pet_name = task.pet.name if task.pet else "Unknown"
        time_str = task.time.strftime("%H:%M") if task.time else "unscheduled"
        status = "✅ Complete" if task.completion_status else "⏳ Pending"
        print(f"  {time_str}: {task.description} ({pet_name}) - {status}")
    print()
    
    # Demonstrate FILTER BY PET
    print("=" * 50)
    print("DEMONSTRATION: filter_tasks(pet_name='Biscuit')")
    print("=" * 50)
    biscuit_tasks = scheduler.filter_tasks(pet_name="Biscuit", include_completed=False)
    print(f"Pending tasks for Biscuit ({len(biscuit_tasks)}):")
    for task in biscuit_tasks:
        print(f"  {task.time.strftime('%H:%M')}: {task.description}")
    print()
    
    # Demonstrate FILTER BY STATUS (include completed)
    print("=" * 50)
    print("DEMONSTRATION: filter_tasks(include_completed=True)")
    print("=" * 50)
    all_tasks = scheduler.filter_tasks(include_completed=True)
    print(f"All tasks including completed ({len(all_tasks)}):")
    for task in all_tasks:
        pet_name = task.pet.name if task.pet else "Unknown"
        time_str = task.time.strftime("%H:%M") if task.time else "unscheduled"
        status = "✅" if task.completion_status else "⏳"
        print(f"  {status} {time_str}: {task.description} ({pet_name})")
    print()
    
    # Generate full schedule
    print("=" * 50)
    print("Generated Schedule")
    print("=" * 50)
    schedule = owner.generate_plan()
    # Print any lightweight warnings generated by the scheduler
    if schedule.warnings:
        print()
        print("Scheduler Warnings")
        print("------------------")
        for w in schedule.warnings:
            print(w)
    if schedule.scheduled_slots:
        for slot in schedule.scheduled_slots:
            start = slot.start_time.strftime("%H:%M")
            end = slot.end_time.strftime("%H:%M")
            pet_name = slot.task.pet.name if slot.task.pet else "Unknown Pet"
            print(f"{start} - {end}: {slot.task.description} ({pet_name})")
    else:
        print("No scheduled tasks yet.")

    if schedule.unmet_tasks:
        print()
        print("Unmet Tasks")
        print("-----------")
        for task in schedule.unmet_tasks:
            pet_name = task.pet.name if task.pet else "Unknown Pet"
            time_str = task.time.strftime("%H:%M") if task.time else "unscheduled"
            print(f"{time_str}: {task.description} ({pet_name})")


if __name__ == "__main__":
    main()
